### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by menhits** [susantokun/ci-susantokun#2]
Database bisa di download di website susantokun di tutorial

**Comment by AAY97** [comment]
di Mananya Gan downloadnya ???

**Comment by menhits** [comment]
Coba buka .website susantokun. Cari di google tutorial CI

Pada tanggal Sen, 18 Mar 2019 21.50, AAY97 <notifications@github.com>
menulis:

**Comment by susantokun** [comment]
> Database bisa di download di website susantokun di tutorial

terima kasih banyak sudah informasikan :dancer: saya baru sempat update repository nya.

**Comment by susantokun** [comment]
@menhits terima kasih banyak sudah informasikan, saya baru sempat update repository nya.

**Comment by susantokun** [comment]
> di Mananya Gan downloadnya ???

@AAY97 di repository sudah ada di dalam folder sql
