### ISSUE TITLE
password hash gagal login

### ISSUE THREAD

**Issue by hamzahjaya** [susantokun/ci-susantokun#4]
tidak bisa login if (!hash_verified($this->input->post('password'), $query->password)) {
            return 3;
}

**Comment by susantokun** [comment]
itu untuk validasi passwordnya salah, coba gunakan repository terbaru jangan lupa databasenya juga.

**Comment by susantokun** [comment]
> tidak bisa login if (!hash_verified($this->input->post('password'), $query->password)) {
> return 3;
> }

itu untuk validasi passwordnya salah, coba gunakan repository terbaru jangan lupa databasenya juga.

**Comment by susantokun** [comment]
@hamzahjaya itu untuk validasi passwordnya salah, coba gunakan repository terbaru dan jangan lupa databasenya gunakan yang ada di repository.
